GaussianNB Demo:

In [ ]:
# Generate a toy dataset for the demo
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])

In [ ]:
# show the two features.
print(X)

[[-1 -1]
 [-2 -1]
 [-3 -2]
 [ 1  1]
 [ 2  1]
 [ 3  2]]


In [ ]:
# The class labels. There are two classes: 1 and 2.
print(Y)

[1 1 1 2 2 2]


In [ ]:
# Create a GaussianNB model and train the model with the dataset.
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X, Y)

GaussianNB()

In [ ]:
# Show the probability of each class.
print(clf.class_prior_)

[0.5 0.5]


In [ ]:
# Show the mean of each feature per class.
print(clf.theta_)

[[-2.         -1.33333333]
 [ 2.          1.33333333]]


In [ ]:
# Show the variance of each feature per class.
print(clf.var_)

[[0.66666667 0.22222223]
 [0.66666667 0.22222223]]


In [ ]:
# Make a prediction on a testing data instance.
print(clf.predict([[-0.8, -1]]))

[1]


MultinomialNB Demo:

In [ ]:
import pandas as pd
# Load the weather data
weather_data = pd.read_csv('Weather.csv')
print(weather_data)
print('\nData shape: ', weather_data.shape)

     Outlook Humidity    Wind Play
0      Sunny     High    Weak   No
1      Sunny     High  Strong   No
2   Overcast     High    Weak  Yes
3       Rain     High    Weak  Yes
4       Rain   Normal    Weak  Yes
5       Rain   Normal  Strong   No
6   Overcast   Normal  Strong  Yes
7      Sunny     High    Weak   No
8      Sunny   Normal    Weak  Yes
9       Rain   Normal    Weak  Yes
10     Sunny   Normal  Strong  Yes
11  Overcast     High  Strong  Yes
12  Overcast   Normal    Weak  Yes
13      Rain     High  Strong   No

Data shape:  (14, 4)


In [ ]:
# Data pre-processing and preparation
# Firstly, we need to encode categorical values
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
coded_data = enc.fit_transform(weather_data)

X = coded_data[:, 0:-1]
y = coded_data[:, -1]

In [ ]:
# Show the fearues
print(X)

[[2. 0. 1.]
 [2. 0. 0.]
 [0. 0. 1.]
 [1. 0. 1.]
 [1. 1. 1.]
 [1. 1. 0.]
 [0. 1. 0.]
 [2. 0. 1.]
 [2. 1. 1.]
 [1. 1. 1.]
 [2. 1. 0.]
 [0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 0.]]


In [ ]:
# Show the class labels: 2 classes: 0 and 1
print(y)

[0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0.]


In [ ]:
# Create and train a CategoricalNB model
from sklearn.naive_bayes import CategoricalNB
clf = CategoricalNB()
clf.fit(X, y)

CategoricalNB()

In [ ]:
# Show alpha
print(clf.alpha)

1.0


In [ ]:
# Show the smoothed empirical log probability for each class.
print(clf.class_log_prior_)

[-1.02961942 -0.44183275]


In [ ]:
# Show the original probability for each class.
print(np.e**clf.class_log_prior_)

[0.35714286 0.64285714]


In [ ]:
# Show empirical log probability of features given a class.
print(clf.feature_log_prob_)

[array([[-2.07944154, -0.98082925, -0.69314718],
       [-0.87546874, -1.09861229, -1.38629436]]), array([[-0.33647224, -1.25276297],
       [-1.01160091, -0.45198512]]), array([[-0.55961579, -0.84729786],
       [-1.01160091, -0.45198512]])]


In [ ]:
# Show the original probability of features given a class.
for i in clf.feature_log_prob_:
  print(np.e**i)

[[0.125      0.375      0.5       ]
 [0.41666667 0.33333333 0.25      ]]
[[0.71428571 0.28571429]
 [0.36363636 0.63636364]]
[[0.57142857 0.42857143]
 [0.36363636 0.63636364]]


In [ ]:
# Perform a prediction on a testing data instance
x_pred = X[5:6]
print(x_pred)
print(clf.predict(x_pred))

[[1. 1. 0.]]
[1.]
